image: openjdk:17

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - docker build -t library-system .
    - docker run -d -p 8080:8080 library-system
  only:
    - main